### ISSUE TITLE
Detect it only 1 channel

### ISSUE THREAD

**Issue by ghost** [SpotlightKid/jack-matchmaker#5]
If there is only one channel, can jack connect this one channel to the all(LR) channels of the system playback port? It's a good simple for a single app, but it's a lot more complicated if it's a Firefox browser.
Here is the actual port of Firefox, when there is only one tab and it is playing stereo there,
Firefox Developer Edition:AudioStream_0_out_0 (Tab 1, Youtube)
Firefox Developer Edition:AudioStream_0_out_1 (Tab 1, Youtube)
Google Translate TTS under only one tab,
Firefox Developer Edition:AudioStream_0_out_0 (Only the left channel sound on my speakers)
And, contains two tabs,
Firefox Developer Edition:AudioStream_0_out_0 (Tab 1, Youtube)
Firefox Developer Edition:AudioStream_0_out_1 (Tab 1, Youtube)
Firefox Developer Edition:AudioStream_1_out_0 (Tab 2, Google Translate)

**Comment by SpotlightKid** [comment]
> If there is only one channel, can jack connect this one channel to the all(LR) channels of the system playback port?

Yes, it can.

You can either specify ports explicitly via the `-e` option:

```
jack-matchmaker -e \
    "My Application:out_1" system:playback_1 \
    "My Application:out_1" system:playback_2
```

Or you can use a regular expression for the output ports to connect to:

```
jack-matchmaker 'My Application:out_1$' 'system:playback_[12]$'
```

Notice that the `-e` option is not used here, so all port specifications are regular expressions. Also note the `$` at the end of each regular expression, so that e.g. the second one matches `system:playback_1` and `system:playback_2`, but not `system:playback_11` or `system:playback:24`.

For the syntax of Python regular expressions, see https://docs.python.org/3/library/re.html#regular-expression-syntax.
